<?php

namespace MedtrainerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudRepository extends EntityRepository
{
}
